21 chatting challenge
pong-nyan/pong-nyan pull request #32
Opened 2023-09-01 08:21 UTC by mikim3

### 중요한 추가사항

- 채널 목록 추가
- 유저가 채널 선택
- 채널에 유저추가
- 채널 내에 유저끼리 대화
- 채널 나가기

https://github.com/pong-nyan/pong-nyan/assets/26201797/d908b4d1-1c80-4c1d-b978-12315944787f

### 동기화 해야 할것

백엔드에서의 채널, 유저리스트 그와 동시에 프론트에 클라이언트의 각각의 채널 안에 속해 있는 클라이언트 목록, 채널목록 동기화, 클라이언트간에 메시지 목록 이 모든게 서로 동기화되어야 한다.

아래 변수들을 통해 그것들을 동기화 시키고 있다.

- 백엔드
    - channelMap
    - userList
    - client소켓의 룸관리(채널관리)
        - ex) client.join(channelId)
- 프론트
    - channelList
    - userList
    - message
    - channelUsers (채널안에 유저)

2023-09-01 08:58 UTC, YeonSeong-Lee requested changes

2023-09-01 08:58 UTC, YeonSeong-Lee commented on backend/src/chat/chat.gateway.ts
> +  handlePrivateMessage(client: any, payload: { targetUserId: string, message: string }) {
이벤트 이름과 통일이 필요해보입니다.

2023-09-01 11:01 UTC, YeonSeong-Lee submitted a review, later dismissed

2023-09-01 12:03 UTC, merged

2023-09-01 12:15 UTC, jhMin95 reviewed
LGTM

2023-09-02 03:13 UTC, mikim3 commented on frontend/src/components/chat/ChatRoom.tsx
> +    });
이번에 닫고 다음 브랜치에 해보겠습니다.